version: "3"
services:
  # DBの設定
  db:
    # コンテナ名の指定
    container_name: rt-c2207_db
    # 2022年7月時点の最新版PostgreSQL
    image: postgres:14.4
    # 環境変数の設定（db.envから読み込む）
    env_file:
      - ./db.env
    # データの永続化（ローカルのtmp/dbディレクトリにマウント）
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  # アプリの設定
  web:
    # コンテナ名の指定
    container_name: rt-c2207_web
    # Dockerfileのあるディレクトリパスを指定
    build: .
    # 環境変数の設定（db.envから読み込む）
    env_file:
      - ./db.env
    # コマンド実行（Rails特有の問題解決とRailsの立ち上げ）
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    # データの永続化（ローカルのカレントディレクトリにマウント）
    volumes:
      - .:/rt-c2207
    # ポートの指定（外部からアクセス時のポート：コンテナからアクセス時のポート）
    ports:
      - "3000:3000"
    # 標準入出力デバイスを設定
    tty: true
    # 依存関係の指定（dbが起動した後に、webが起動する）
    depends_on:
      - db
